# Generated by Django 4.2.7 on 2025-08-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0011_remove_job_seeker_skills_job_seeker_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_seeker',
            name='CareerObjective',
        ),
        migrations.RemoveField(
            model_name='job_seeker',
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='job_seeker',
            name='Experience',
        ),
        migrations.RemoveField(
            model_name='job_seeker',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='job_seeker',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='job_seeker',
            name='others_link',
        ),
        migrations.RemoveField(
            model_name='job_seeker',
            name='projects_name',
        ),
        migrations.RemoveField(
            model_name='job_seeker',
            name='skills',
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='Resume',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
