# Generated by Django 4.2.7 on 2026-03-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0012_remove_job_seeker_careerobjective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_seeker',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
