# Generated by Django 4.2.7 on 2026-03-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0013_job_seeker_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_seeker',
            name='CareerObjective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='Contact',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='Experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='github_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='others_link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='projects_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='skills',
            field=models.ManyToManyField(blank=True, to='job_seeker.skill'),
        ),
    ]
