# Generated by Django 4.2.7 on 2025-08-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='About',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Company_Logo',
            field=models.ImageField(null=True, upload_to='media/images'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Company_number',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='company_mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
